# ===== OCR Character Detection Config =====
# รูปแบบ: keyword1+keyword2-keyword3=OutputName
# + หมายถึง ต้องมีคำนี้ (AND)
# - หมายถึง ห้ามมีคำนี้ (NOT)
# = ชื่อที่ใช้ในการบันทึกไฟล์

[herowant]
name1=First+Emperor=UltraQinShi
name2=Underworld+King+Hades=UltraHades
name3=Lone+Sorcerer+Tesla=UltraTesla
name4=Sun+God+Apollo=UltraApollo
name5=Qin+Shi-Sally=QinShi
name6=Hades=Hades
name7=Tesla=Tesla
name8=Apollo=Apollo


[gearwant]
gear1=Leonard+Headphones=LH
gear2=Leonard+Tough+Watch=LTW
gear3=Leonard+Quick+Visor=LQV
gear4=Leonard+Mysterious+Syringe=LMS
gear5=Leonard+Quick+Belt=LQB
gear6=Leonard+Mysterious+Bag=LMBag
gear7=Leonard+Tough+Vest=LTV
gear8=Leonard+Mysterious+Bomb=LMBomb
gear9=Leonard+Tough+Dumbbell=LTD
gear10=Christmas+Holy+Shield=ChristShield
gear11=Christmas+Holy+Ring=ChristRing
gear12=Christmas+Holy+Boots=ChristBoots
gear13=Christmas+Holy+Gun=ChristGun
gear14=Christmas+Hammer=ChristHammer
gear15=Xmas+Hammer=ChristHammer
gear16=Christmas+Holy+Bow=ChristBow
gear17=Christmas+Tree=ChristTree
gear18=Christmas+Hat=ChristHat
gear19=Christmas+Candle=ChristCandle
gear20=Christmas+Candy=ChristCandy
gear21=Hare+Chain=NYChain
gear22=Snake+Hat=NYHat
gear23=Blue+Dragon+Necklace=NYNecklace
gear24=Blue+Dragon+Shield=NYShield
gear25=Flower+Comb=NYFlower
gear26=Demon+Mask=NYMask
gear27=Hagoita=NYHagoita
gear28=Blue+Dragon+Whip=NYWhip



